spring:
  application:
    name: MeKluppie Web App
  config:
    import:
      - classpath:services-application.yaml
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://solidcommunity.net/
