spring:
  application:
    name: MeKluppie Web App
  config:
    import:
      - classpath:services-application.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://solidcommunity.net/
logging:
  level:
    root: info
    org.springframework.security.oauth2: TRACE
    com.nimbusds: DEBUG
